server:
  port: 8080

spring:
 datasource:
   url: jdbc:h2:mem:testdb
   driverClassName: org.h2.Driver
 h2:
   console:
     enabled: true


 jpa:
   database-platform: org.hibernate.dialect.H2Dialect

logging:
 level:
   root: info
   pattern:
   console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

formatDate: dd.MM.yyyy
infoPost: post=10